//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirthdayBook {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BirthdayBook.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files-def.
        /// </summary>
        internal static string _ALLFILES_ {
            get {
                return ResourceManager.GetString("[ALLFILES]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Book-def.
        /// </summary>
        internal static string _BBOOK_ {
            get {
                return ResourceManager.GetString("[BBOOK]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday-def.
        /// </summary>
        internal static string _BIRTHDAY_ {
            get {
                return ResourceManager.GetString("[BIRTHDAY]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel-def.
        /// </summary>
        internal static string _CANCEL_ {
            get {
                return ResourceManager.GetString("[CANCEL]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close-def.
        /// </summary>
        internal static string _CLOSE_ {
            get {
                return ResourceManager.GetString("[CLOSE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name-def.
        /// </summary>
        internal static string _COLUMN_NAME_ {
            get {
                return ResourceManager.GetString("[COLUMN NAME]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Number-def.
        /// </summary>
        internal static string _COLUMN_NUMBER_ {
            get {
                return ResourceManager.GetString("[COLUMN NUMBER]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset-def.
        /// </summary>
        internal static string _DATASET_ {
            get {
                return ResourceManager.GetString("[DATASET]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name-def.
        /// </summary>
        internal static string _DISPLAY_NAME_ {
            get {
                return ResourceManager.GetString("[DISPLAY NAME]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name-def.
        /// </summary>
        internal static string _ENGLISH_NAME_ {
            get {
                return ResourceManager.GetString("[ENGLISH NAME]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit-def.
        /// </summary>
        internal static string _EXIT_ {
            get {
                return ResourceManager.GetString("[EXIT]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error-def.
        /// </summary>
        internal static string _FATALERROR_ {
            get {
                return ResourceManager.GetString("[FATALERROR]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-def.
        /// </summary>
        internal static string _FILE_ {
            get {
                return ResourceManager.GetString("[FILE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name-def.
        /// </summary>
        internal static string _FILE_NAME_ {
            get {
                return ResourceManager.GetString("[FILE NAME]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File of Type-def.
        /// </summary>
        internal static string _FILE_OF_TYPE_ {
            get {
                return ResourceManager.GetString("[FILE OF TYPE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting-def.
        /// </summary>
        internal static string _GREETING_ {
            get {
                return ResourceManager.GetString("[GREETING]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information-def.
        /// </summary>
        internal static string _INFORMATION_ {
            get {
                return ResourceManager.GetString("[INFORMATION]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Culture-def.
        /// </summary>
        internal static string _INSTALLED_CULTURE_ {
            get {
                return ResourceManager.GetString("[INSTALLED CULTURE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed UI Culture-def.
        /// </summary>
        internal static string _INSTALLED_UI_CULTURE_ {
            get {
                return ResourceManager.GetString("[INSTALLED UI CULTURE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock in-def.
        /// </summary>
        internal static string _LOOK_IN_ {
            get {
                return ResourceManager.GetString("[LOOK IN]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name-def.
        /// </summary>
        internal static string _NAME_ {
            get {
                return ResourceManager.GetString("[NAME]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Name-def.
        /// </summary>
        internal static string _NATIVE_NAME_ {
            get {
                return ResourceManager.GetString("[NATIVE NAME]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Row found-def.
        /// </summary>
        internal static string _NOROWERROR_ {
            get {
                return ResourceManager.GetString("[NOROWERROR]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK-def.
        /// </summary>
        internal static string _OK_ {
            get {
                return ResourceManager.GetString("[OK]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-def.
        /// </summary>
        internal static string _OPEN_ {
            get {
                return ResourceManager.GetString("[OPEN]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Number-def.
        /// </summary>
        internal static string _ROW_NUMBER_ {
            get {
                return ResourceManager.GetString("[ROW NUMBER]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save-def.
        /// </summary>
        internal static string _SAVE_ {
            get {
                return ResourceManager.GetString("[SAVE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as-def.
        /// </summary>
        internal static string _SAVE_AS_ {
            get {
                return ResourceManager.GetString("[SAVE AS]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as type-def.
        /// </summary>
        internal static string _SAVE_AS_TYPE_ {
            get {
                return ResourceManager.GetString("[SAVE AS TYPE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in-def.
        /// </summary>
        internal static string _SAVE_IN_ {
            get {
                return ResourceManager.GetString("[SAVE IN]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Culture-def.
        /// </summary>
        internal static string _SELECT_CULTURE_ {
            get {
                return ResourceManager.GetString("[SELECT CULTURE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select UI Culture-def.
        /// </summary>
        internal static string _SELECT_UI_CULTURE_ {
            get {
                return ResourceManager.GetString("[SELECT UI CULTURE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Culture-def.
        /// </summary>
        internal static string _SETCULTURE_ {
            get {
                return ResourceManager.GetString("[SETCULTURE]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application startup from allows you to reset the culture and user interrface culture before starting an application. Use exit to terminate immediately. -def.
        /// </summary>
        internal static string _SETCULTURELABEL_ {
            get {
                return ResourceManager.GetString("[SETCULTURELABEL]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Cultures-def.
        /// </summary>
        internal static string _SHOW_ALL_CULTURES_ {
            get {
                return ResourceManager.GetString("[SHOW ALL CULTURES]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary-def.
        /// </summary>
        internal static string _SUMMARY_ {
            get {
                return ResourceManager.GetString("[SUMMARY]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files-def.
        /// </summary>
        internal static string _TEXTFILES_ {
            get {
                return ResourceManager.GetString("[TEXTFILES]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML-def.
        /// </summary>
        internal static string _XML_ {
            get {
                return ResourceManager.GetString("[XML]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
    }
}
